@startuml
!pragma layout smetana
top to bottom direction

[*] --> NotLoggedIn

state NotLoggedIn {
    [*] --> NotLoggedInIndex : Start side
    NotLoggedInIndex : Her kan man se udvalg af cupcakes

    NotLoggedInIndex --> LoginDialog : On Click "Login"
    LoginDialog --> LoginDialog : Fejl i login
    LoginDialog --> CreateUser : On Click "Opret bruger"

    state CreateUser {
        CreateUser : Opret ny bruger med email + password
        CreateUser --> CreateUser : Fejl i oprettelse
        CreateUser --> NotLoggedInIndex : Bruger oprettet
    }
}

state LoggedIn {
    LoggedInIndex : Logged in
    LoginDialog --> LoggedInIndex : Gyldigt login
    CupcakeSelection : Hvis ikke logget ind, view only
    CupcakeSelection: Vælg bund, top og antal
    LoggedInIndex --> CupcakeSelection
    CupcakeSelection --> CupcakeSelection : Læg i kurv
    CupcakeSelection --> Cart : On Click "Kurv"
    CupcakeSelection --> Orders : On Click "Ordrer"
    CupcakeSelection --> NotLoggedInIndex : Logout

    Cart --> LoggedInIndex : Click "Logo" or "Home"
    Cart --> Orders : Click "Bestil"


        Orders : Admin views all orders
        Orders : User views personal orders
        Orders --> LoggedInIndex : Click "Logo" or "Home"

}
@enduml
